export const queryKeys = {
    GET_APPS: "GET_APPS",
    GET_APP_DETAIL: "GET_APP_DETAIL",
    GET_APP_CONTENT: "GET_APP_CONTENT",
    GET_APP_USERS: "GET_APP_USERS",
    LIST_APP_MEDIA: "LIST_APP_MEDIA",
};
